In [2]:
# Импортируем нужные библотеки
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as sts
%matplotlib inline

In [3]:
# Выберите ваше любимое непрерывное распределение
# Распределение Максвела

# Сгенерируйте из него выборку объёма 1000
sample = sts.maxwell.rvs(size=1000)

In [13]:
# постройте гистограмму выборки и нарисуйте поверх неё теоретическую плотность распределения вашей случайной величины
plt.hist(sample, bins=15, density=True)
plt.ylabel('Fraction of samples')
plt.xlabel('$x$')

Text(0.5, 0, '$x$')

In [8]:
# при трёх и более значениях n (например, 5, 10, 50) сгенерируйте 1000 выборок объёма n
n_sizes = np.array([5,10,50])
num_of_samples = 1000

samples = {}

for n in n_sizes:
    samples[n] = []
    for j in range(num_of_samples):
        samples[n].append(sts.maxwell.rvs(size=n))
        
samples

{5: [array([1.22944361, 1.39459628, 1.53789305, 1.23220364, 2.15459216]),
  array([0.76616282, 2.21530746, 2.00786381, 1.90896979, 0.92808512]),
  array([0.58880386, 0.44516856, 0.69574523, 2.21955173, 0.40447007]),
  array([1.39466901, 0.51137733, 0.85997499, 0.98933388, 1.25467186]),
  array([2.35055872, 1.32972317, 3.30209158, 1.11274817, 1.16379423]),
  array([1.96944818, 1.02727274, 2.05054996, 1.37065087, 1.22427311]),
  array([0.47150399, 1.65616275, 1.57226226, 0.88371294, 1.02336928]),
  array([1.77224723, 1.35873212, 2.13036529, 2.40310544, 2.31900974]),
  array([2.76325764, 1.92458886, 1.470011  , 1.06758195, 1.14419017]),
  array([2.50460545, 2.36813077, 1.24928955, 1.93591135, 0.60824396]),
  array([2.32727451, 2.01742591, 0.8770298 , 2.10406572, 2.05543704]),
  array([1.52925443, 1.59079252, 2.0332099 , 2.42601367, 1.68336591]),
  array([1.26569433, 1.8041152 , 1.22226177, 1.95270283, 1.4034812 ]),
  array([1.13817743, 1.82879846, 2.62952884, 0.81892992, 1.70219676]),
  a